### ISSUE TITLE
Cek semua langkah tidak ada kesalahan

### ISSUE THREAD

**Issue by priyandari** [SelmiMaulida/UAS-ProgKomp#1]
Pilih Negara yang ingin di edit barangnya:
        1. Singa
Pilihan : 1

Daftar kategori :
Kategori kosong
1. Tambah Barang
2. Hapus Barang
Pilihan :

**Comment by tasyasanti** [comment]
Mengubah kalimat "Daftar kategori :" menjadi "Daftar barang"
Mengubah kalimat "Kategori kosong:" menjadi "Barang kosong"
Mengubah kalimat "Kategori telah ditambahkan" menjadi "Barang telah ditambahkan"
Mengubah kalimat "Masukkan harga" menjadi "Masukkan harga barang dalam angka saja"
Mengubah kalimat "Masukkan nilai kurs ke INA" menjadi "Masukkan nilai kurs ke INA (Hanya Angka)"
Mengubah kalimat "Produk sudah ditambahkan" menjadi "Barang sudah ditambahkan"
