### ISSUE TITLE
User firendly

### ISSUE THREAD

**Issue by priyandari** [SelmiMaulida/UAS-ProgKomp#2]
Berikan kemudahan kepada pengguna program dengan pertanyaan dan informasi yang jelas

**Comment by tasyasanti** [comment]
Mengubah kalimat "do you want to quit?" menjadi "Apakah Anda ingin keluar dari menu 1. List Negara?" (disesuaikan dengan menu yang sedang dipilih)
Mengubah kalimat "do you want to quit?" menjadi "Apakah Anda ingin keluar dari menu 2. Mulai Pendataan Pesanan?"
Mengubah kalimat "start again?" menjadi "Apakah Anda ingin kembali ke menu awal?"
Menambahkan kalimat untuk memperjelas informasi pada "Pilih barang yang ingin di hapus" menjadi "Pilih barang yang ingin di hapus(Jika ada pesanan, maka pesanan otomatis terhapus):"
Mengubah kalimat "do you want to quit" menjadi "Apakah edit Barang Negara sudah selesai?" ketika pengguna telah selesai mengedit barang.
